import { PrismaClient, type ItineraryCategory } from "@prisma/client";

/**
 * Gives every package a cover photo and a small gallery, so the site reads as
 * finished while the agency's own photography is being gathered.
 * Run with: npm run db:seed:photos
 *
 * ⚠️ THESE PHOTOGRAPHS ARE NOT REAL. They were generated by an image model in
 * September 2026 and depict no actual place. They are deliberately generic —
 * a valley, a pass, a courtyard — and none of them purports to be a named
 * landmark, precisely so that nobody books a trip expecting the building in
 * the picture. They are placeholders and must be replaced with the agency's
 * own pictures before the site takes real bookings. docs/demo-photos.md says
 * how to clear them.
 *
 * The files live in public/media/packages, so the URLs are same-origin and
 * survive without any third-party host staying up.
 *
 * Deterministic: choices are seeded from each package's slug, so re-running
 * produces the same assignment rather than reshuffling the site's appearance
 * under someone who just looked at it.
 */

const prisma = new PrismaClient();

/** Hosts considered a local development database. */
const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1", "::1", "[::1]"]);

/**
 * This script takes no connection argument — it writes wherever DATABASE_URL
 * points, which on a machine configured for deploys is production. It sets
 * imagery every visitor sees, so an unnoticed production DATABASE_URL matters.
 *
 * Run against a non-local database with:
 *   npm run db:seed:photos -- --allow-production
 */
function assertSafeTarget(): void {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set — nothing to seed into.");

  let host: string;
  try {
    host = new URL(url).hostname;
  } catch {
    throw new Error("DATABASE_URL could not be parsed as a connection string; refusing to seed.");
  }

  if (LOCAL_HOSTS.has(host)) return;

  if (process.argv.includes("--allow-production")) {
    console.warn(`⚠️  --allow-production: seeding demo photos into NON-LOCAL database at ${host}\n`);
    return;
  }

  throw new Error(
    `Refusing to seed: DATABASE_URL points at "${host}", which is not a local database.\n` +
      "Re-run with --allow-production if that is really what you want."
  );
}

const BASE = "/media/packages";

type Shot = { file: string; caption: string };

const SHOTS: Record<string, Shot> = {
  valley: { file: "valley-farmhouses.webp", caption: "Farmhouses among the terraces, western valleys" },
  dzong: { file: "dzong-ridge.webp", caption: "A dzong above the river" },
  cham: { file: "cham-dance.webp", caption: "Masked cham dancers at a tshechu" },
  wheels: { file: "prayer-wheels.webp", caption: "Prayer wheels along a monastery wall" },
  courtyard: { file: "monastery-courtyard.webp", caption: "A monastery courtyard in late light" },
  flags: { file: "pass-prayer-flags.webp", caption: "Prayer flags on a high pass" },
  camp: { file: "alpine-camp.webp", caption: "Camp beside a glacial lake" },
  yaks: { file: "yak-pasture.webp", caption: "Yaks on the high pasture" },
  bridge: { file: "suspension-bridge.webp", caption: "A flagged footbridge over the gorge" },
  cranes: { file: "cranes-wetland.webp", caption: "Black-necked cranes at first light" },
  forest: { file: "forest-river.webp", caption: "Broadleaf forest and a clear river" },
  rhodo: { file: "rhododendron-path.webp", caption: "Rhododendrons in spring bloom" },
  lodge: { file: "lodge-terrace.webp", caption: "A lodge terrace at dusk" },
};

/**
 * Which scenes suit which kind of trip. Ordered best-first: the cover is
 * drawn from the front of the list, so a trekking package leads on mountains
 * rather than on a courtyard.
 */
const BY_CATEGORY: Record<ItineraryCategory, (keyof typeof SHOTS)[]> = {
  TREKKING: ["camp", "yaks", "flags", "bridge", "valley", "forest"],
  CULTURAL: ["dzong", "cham", "courtyard", "wheels", "valley", "flags"],
  WILDLIFE: ["cranes", "forest", "rhodo", "yaks", "valley", "bridge"],
  HONEYMOON: ["lodge", "valley", "rhodo", "courtyard", "flags", "forest"],
};

/**
 * Every scene, for the places and articles that have no category to sort by.
 * Ordered so that consecutive items look different from one another, since
 * destinations are rendered as a four-across grid and neighbours are seen
 * together.
 */
const ALL_SHOTS: (keyof typeof SHOTS)[] = [
  "valley", "dzong", "camp", "cranes", "courtyard", "yaks", "rhodo",
  "wheels", "bridge", "forest", "cham", "lodge", "flags",
];

/**
 * Articles get a scene that matches what they are about rather than a
 * rotation: three of them, each on a subject with an obvious picture, and a
 * visa explainer under a photograph of rhododendrons would just look random.
 */
const BY_ARTICLE: Record<string, keyof typeof SHOTS> = {
  "visa-and-entry-requirements-for-bhutan": "dzong",
  "bhutans-sustainable-development-fee-explained": "valley",
  "best-time-to-visit-bhutan": "rhodo",
};

/**
 * Rotates the category's list by the package's position within its category,
 * rather than by a hash of the slug.
 *
 * A hash looks more principled and is worse here: over 29 packages and pools
 * of six it clumped badly, and nine covers came out as the same photograph.
 * On a listing page that repetition is the thing that gives a placeholder
 * away. Cycling by position spreads the pool as evenly as it can go, and
 * stays deterministic because the ordering is by slug.
 */
function shotsFor(indexInCategory: number, category: ItineraryCategory) {
  const pool = BY_CATEGORY[category];
  const offset = indexInCategory % pool.length;
  return pool.map((_, i) => SHOTS[pool[(offset + i) % pool.length]]);
}

async function main() {
  assertSafeTarget();

  const replace = process.argv.includes("--replace");
  const itineraries = await prisma.itinerary.findMany({
    orderBy: { slug: "asc" },
    include: { _count: { select: { photos: true } } },
  });

  let covered = 0;
  let galleried = 0;
  let skipped = 0;

  // Position within the category, in slug order, so the rotation below is
  // both evenly spread and the same on every run.
  const seenInCategory = new Map<ItineraryCategory, number>();

  for (const itinerary of itineraries) {
    const indexInCategory = seenInCategory.get(itinerary.category) ?? 0;
    seenInCategory.set(itinerary.category, indexInCategory + 1);
    const ordered = shotsFor(indexInCategory, itinerary.category);

    // A real cover beats a generated one, so an existing value is left alone.
    const needsCover = replace || !itinerary.coverPhotoUrl;
    const needsGallery = replace || itinerary._count.photos === 0;

    if (!needsCover && !needsGallery) {
      skipped++;
      continue;
    }

    if (needsCover) {
      await prisma.itinerary.update({
        where: { id: itinerary.id },
        data: { coverPhotoUrl: `${BASE}/${ordered[0].file}` },
      });
      covered++;
    }

    if (needsGallery) {
      // Four is enough to fill the gallery grid without the repetition
      // becoming obvious across a pool this size.
      const gallery = ordered.slice(0, 4);
      await prisma.$transaction([
        prisma.itineraryPhoto.deleteMany({ where: { itineraryId: itinerary.id } }),
        prisma.itineraryPhoto.createMany({
          data: gallery.map((shot, position) => ({
            itineraryId: itinerary.id,
            position,
            url: `${BASE}/${shot.file}`,
            caption: shot.caption,
          })),
        }),
      ]);
      galleried++;
    }

    console.log(`  ${itinerary.slug}: cover ${needsCover ? "set" : "kept"}, gallery ${needsGallery ? "set" : "kept"}`);
  }

  // --- the homepage's other two picture grids ------------------------------
  // Destinations and travel-guide articles are shown alongside the packages
  // on the homepage, so filling only the packages leaves it half-dressed.
  const destinations = await prisma.destination.findMany({ orderBy: { slug: "asc" } });
  let places = 0;
  for (const [i, destination] of destinations.entries()) {
    if (destination.photoUrl && !replace) continue;
    await prisma.destination.update({
      where: { id: destination.id },
      data: { photoUrl: `${BASE}/${SHOTS[ALL_SHOTS[i % ALL_SHOTS.length]].file}` },
    });
    places++;
  }

  const articles = await prisma.article.findMany({ orderBy: { slug: "asc" } });
  let written = 0;
  for (const [i, article] of articles.entries()) {
    if (article.coverPhotoUrl && !replace) continue;
    const key = BY_ARTICLE[article.slug] ?? ALL_SHOTS[i % ALL_SHOTS.length];
    await prisma.article.update({
      where: { id: article.id },
      data: { coverPhotoUrl: `${BASE}/${SHOTS[key].file}` },
    });
    written++;
  }

  console.log(
    `\n${covered} cover${covered === 1 ? "" : "s"} and ${galleried} galler${galleried === 1 ? "y" : "ies"} set, ${skipped} left alone.`
  );
  console.log(`${places} destination${places === 1 ? "" : "s"} and ${written} article${written === 1 ? "" : "s"} given a picture.`);
  if (skipped > 0 && !replace) console.log("Pass --replace to overwrite those too.");
  console.log("\nReminder: these are generated placeholders, not photographs of real places.");
  console.log("Guide portraits are deliberately NOT seeded — see docs/demo-photos.md.");
}

main()
  .catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
