/**
 * The real pixel size of every capture in public/captures.
 *
 * GENERATED by video/build-capture-manifest.mjs — do not edit by hand.
 * BrowserFrame reads it to work out how far a pan can travel; see that file.
 */
export const CAPTURE_SIZES: Record<string, { width: number; height: number }> = {
  "about-full": {
    "width": 1800,
    "height": 2264
  },
  "about": {
    "width": 1800,
    "height": 1125
  },
  "admin-content": {
    "width": 1800,
    "height": 1125
  },
  "admin-knowledge": {
    "width": 1800,
    "height": 1125
  },
  "admin-overview": {
    "width": 1800,
    "height": 1125
  },
  "admin-packages": {
    "width": 1800,
    "height": 1125
  },
  "article-sdf-full": {
    "width": 1800,
    "height": 2101
  },
  "article-sdf": {
    "width": 1800,
    "height": 1125
  },
  "assistant-answer-plan": {
    "width": 1800,
    "height": 1125
  },
  "assistant-answer-sdf-full": {
    "width": 1800,
    "height": 2211
  },
  "assistant-answer-sdf": {
    "width": 1800,
    "height": 1125
  },
  "assistant-empty-full": {
    "width": 1800,
    "height": 2211
  },
  "assistant-empty": {
    "width": 1800,
    "height": 1125
  },
  "assistant-memory-1": {
    "width": 1800,
    "height": 1125
  },
  "assistant-memory-2": {
    "width": 1800,
    "height": 1125
  },
  "assistant-memory-full": {
    "width": 1800,
    "height": 2220
  },
  "assistant-thinking": {
    "width": 1800,
    "height": 1125
  },
  "assistant-typing": {
    "width": 1800,
    "height": 1125
  },
  "contact": {
    "width": 1800,
    "height": 1125
  },
  "custom-tour-full": {
    "width": 1800,
    "height": 2734
  },
  "custom-tour": {
    "width": 1800,
    "height": 1125
  },
  "dashboard-traveler": {
    "width": 1800,
    "height": 1125
  },
  "destination-paro-full": {
    "width": 1800,
    "height": 3004
  },
  "destination-paro": {
    "width": 1800,
    "height": 1125
  },
  "destinations-full": {
    "width": 1800,
    "height": 2109
  },
  "destinations": {
    "width": 1800,
    "height": 1125
  },
  "faq": {
    "width": 1800,
    "height": 1125
  },
  "flights": {
    "width": 1800,
    "height": 1125
  },
  "gallery": {
    "width": 1800,
    "height": 1125
  },
  "guides": {
    "width": 1800,
    "height": 1125
  },
  "home-chat-button": {
    "width": 1800,
    "height": 1125
  },
  "home-full": {
    "width": 1800,
    "height": 12422
  },
  "home": {
    "width": 1800,
    "height": 1125
  },
  "hotels": {
    "width": 1800,
    "height": 1125
  },
  "login": {
    "width": 1800,
    "height": 1125
  },
  "nav-megamenu": {
    "width": 1800,
    "height": 1125
  },
  "package-detail-full": {
    "width": 1800,
    "height": 6561
  },
  "package-detail": {
    "width": 1800,
    "height": 1125
  },
  "package-trek": {
    "width": 1800,
    "height": 1125
  },
  "packages-full": {
    "width": 1800,
    "height": 9800
  },
  "packages": {
    "width": 1800,
    "height": 1125
  },
  "phone-home": {
    "width": 1170,
    "height": 2532
  },
  "phone-package": {
    "width": 1170,
    "height": 2532
  },
  "phone-widget-answer": {
    "width": 1170,
    "height": 2532
  },
  "phone-widget-closed": {
    "width": 1170,
    "height": 2532
  },
  "phone-widget-open": {
    "width": 1170,
    "height": 2532
  },
  "register": {
    "width": 1800,
    "height": 1125
  },
  "travel-guide": {
    "width": 1800,
    "height": 1125
  },
  "vehicles": {
    "width": 1800,
    "height": 1125
  },
  "vendor-guide-register-full": {
    "width": 1800,
    "height": 2046
  },
  "vendor-guide-register": {
    "width": 1800,
    "height": 1125
  },
  "widget-answer-home": {
    "width": 1800,
    "height": 1125
  },
  "widget-answer-sdf": {
    "width": 1800,
    "height": 1125
  },
  "widget-closed-package": {
    "width": 1800,
    "height": 1125
  },
  "widget-open-greeting": {
    "width": 1800,
    "height": 1125
  },
  "widget-thinking": {
    "width": 1800,
    "height": 1125
  },
  "widget-typing": {
    "width": 1800,
    "height": 1125
  }
};
