/**
 * The client-story narration: when each line is spoken, and the on-screen text
 * the script asks for alongside it.
 *
 * GENERATED by video/build-client-vo.mjs — do not edit by hand.
 *
 * `onScreen` is the client's own wording, not a caption written for them.
 */
export type ClientLine = { id: string; start: number; end: number; text: string; onScreen: string | null };

export const CLIENT_VO_DURATION = 67.109;

export const CLIENT_VO: ClientLine[] = [
  {
    "id": "hook",
    "start": 0,
    "end": 3.16,
    "text": "Here's what I built for a travel client in Bhutan.",
    "onScreen": "Building a travel website for a real client 🇧🇹"
  },
  {
    "id": "start",
    "start": 3.16,
    "end": 11.95,
    "text": "I started with the idea of creating a modern platform where travelers could discover Bhutan and plan their journey.",
    "onScreen": "DTT BHUTAN — CLIENT PROJECT"
  },
  {
    "id": "building",
    "start": 11.95,
    "end": 20.9,
    "text": "First, I built the core website — the interface, travel pages, user flows, and the functionality behind them.",
    "onScreen": "DESIGN → DEVELOPMENT → FUNCTIONALITY"
  },
  {
    "id": "hood1",
    "start": 20.9,
    "end": 24.87,
    "text": "But a website isn't just what you see on the screen.",
    "onScreen": null
  },
  {
    "id": "hood2",
    "start": 24.87,
    "end": 31.43,
    "text": "I also built the backend, database architecture, authentication, and APIs powering the experience.",
    "onScreen": null
  },
  {
    "id": "aiIdea",
    "start": 31.43,
    "end": 39.96,
    "text": "Once the website was working, I wanted visitors to have someone they could actually ask about Bhutan.",
    "onScreen": "Then I wanted to take it further…"
  },
  {
    "id": "assistant",
    "start": 39.96,
    "end": 44.52,
    "text": "So I built an AI Travel Assistant and integrated it directly into the website.",
    "onScreen": "AI TRAVEL ASSISTANT"
  },
  {
    "id": "howItWorks",
    "start": 44.52,
    "end": 53.61,
    "text": "It can connect the conversation with travel knowledge, so the assistant can provide more relevant information about Bhutan.",
    "onScreen": null
  },
  {
    "id": "result",
    "start": 53.61,
    "end": 56,
    "text": "And this is the final result.",
    "onScreen": "DTT BHUTAN"
  },
  {
    "id": "brand1",
    "start": 56,
    "end": 60.18,
    "text": "This is one of the projects I'm building as a freelance web developer.",
    "onScreen": "JAMBAYANG.COM"
  },
  {
    "id": "brand2",
    "start": 60.18,
    "end": 65.27,
    "text": "I'm Jambayang, and I build websites and digital experiences for businesses.",
    "onScreen": null
  },
  {
    "id": "end",
    "start": 65.27,
    "end": 67.11,
    "text": "More builds coming soon.",
    "onScreen": "Building. Designing. Shipping."
  }
];
