/**
 * Code shown in the video, sliced verbatim out of the DTT Bhutan repository.
 *
 * GENERATED by video/extract-snippets.mjs — do not edit by hand. Each entry
 * carries the file it came from and the line the excerpt starts at, so any
 * frame of the film can be looked up in the repo. Re-run the extractor after
 * changing a source file and the video follows it.
 */
export type Snippet = { path: string; startLine: number; code: string };

export const SNIPPETS = {
  "bookingRoute": {
    "path": "src/app/api/bookings/route.ts",
    "startLine": 7,
    "code": "export async function POST(req: NextRequest) {\n  const user = await getCurrentUser();\n  if (!user) {\n    return NextResponse.json({ error: \"Log in to book\" }, { status: 401 });\n  }\n  if (user.role !== \"TRAVELER\") {\n    return NextResponse.json(\n      { error: \"Only traveler accounts can create bookings\" },\n      { status: 403 }\n    );\n  }\n\n  const body = await req.json().catch(() => null);\n  const parsed = bookingSchema.safeParse(body);\n  if (!parsed.success) {\n    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });\n  }\n\n  try {\n    const booking = await createBooking(user.id, parsed.data);\n    await notifyBookingCreated(booking.id);\n    return NextResponse.json(booking, { status: 201 });\n  } catch (err) {\n    if (err instanceof BookingConflictError) {\n      return NextResponse.json({ error: err.message }, { status: 409 });\n    }\n    if (err instanceof BookingNotFoundError) {\n      return NextResponse.json({ error: err.message }, { status: 404 });\n    }\n    throw err;\n  }"
  },
  "validation": {
    "path": "src/lib/validation.ts",
    "startLine": 132,
    "code": "export const itineraryBookingSchema = z.object({\n  type: z.literal(\"ITINERARY\"),\n  itineraryId: z.string().min(1),\n  startDate: z.coerce.date(),\n  travelers: z.coerce.number().int().min(1).max(30),\n  notes: z.string().max(2000).optional(),\n});\n"
  },
  "auth": {
    "path": "src/lib/auth.ts",
    "startLine": 81,
    "code": "export async function requireRole(...roles: Role[]) {\n  const user = await requireUser();\n  if (!roles.includes(user.role)) {\n    throw new AuthError(\"Not authorized\");\n  }\n  return user;\n}\n\nexport class AuthError extends Error {}\n"
  },
  "schemaItinerary": {
    "path": "prisma/schema.prisma",
    "startLine": 342,
    "code": "model Itinerary {\n  id             String            @id @default(cuid())\n  title          String\n  slug           String            @unique\n  summary        String\n  description    String?\n  durationDays   Int\n  pricePerPerson Decimal           @db.Decimal(10, 2)\n  maxGroupSize   Int?\n  difficulty     TripDifficulty    @default(EASY)\n  category       ItineraryCategory @default(CULTURAL)\n  status         ItineraryStatus   @default(DRAFT)\n  coverPhotoUrl  String?\n  includes       String[] // e.g. \"Licensed guide\", \"All ground transport\", \"3-star hotels\"\n  excludes       String[] // e.g. \"International flights\", \"Visa fee\", \"Personal expenses\"\n  createdAt      DateTime          @default(now())\n  updatedAt      DateTime          @updatedAt\n\n  days     ItineraryDay[]\n  bookings ItineraryBooking[]\n  departures Departure[]\n  lodgings   ItineraryLodging[]"
  },
  "chatRoute": {
    "path": "src/app/api/chat/route.ts",
    "startLine": 45,
    "code": "export async function POST(req: NextRequest) {\n  const ip =\n    req.headers.get(\"x-forwarded-for\")?.split(\",\")[0]?.trim() ||\n    req.headers.get(\"x-real-ip\") ||\n    \"unknown\";\n\n  if (isChatRateLimited(ip)) {\n    return NextResponse.json(\n      { error: \"You're sending messages a little too quickly. Please wait a moment and try again.\" },\n      { status: 429 }\n    );\n  }\n\n  const body = await req.json().catch(() => null);\n  const parsed = chatRequestSchema.safeParse(body);\n  if (!parsed.success) {\n    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });\n  }\n  const { message, conversationId: requestedConversationId } = parsed.data;\n\n  // A conversationId the client sends might be stale, expired, or simply\n  // wrong — that's not a client error, it just means we start a fresh one\n  // and hand back its real id. Never 404 for this.\n  const existing = requestedConversationId"
  },
  "provider": {
    "path": "src/lib/ai/provider.ts",
    "startLine": 108,
    "code": "export function getAiProvider(): AiProvider {\n  const configured = process.env.AI_PROVIDER?.trim();\n  if (!configured) warnMissingProvider();\n  const name = (configured || \"ollama\") as AiProviderName;\n\n  switch (name) {\n    case \"ollama\":\n      return new OllamaProvider();\n    case \"anthropic\":\n      return new AnthropicProvider();\n    case \"gemini\":\n      return new GeminiProvider();\n    default: {\n      const exhaustiveCheck: never = name;\n      throw new Error(`Unknown AI_PROVIDER: ${exhaustiveCheck}`);\n    }\n  }"
  },
  "tools": {
    "path": "src/lib/ai/tools.ts",
    "startLine": 137,
    "code": "async function getPackageDetails(args: { titleOrSlug: string }) {\n  const itinerary = await prisma.itinerary.findFirst({\n    where: {\n      status: \"PUBLISHED\",\n      OR: [\n        { slug: args.titleOrSlug },\n        { title: { equals: args.titleOrSlug, mode: \"insensitive\" } },\n        { title: { contains: args.titleOrSlug, mode: \"insensitive\" } },\n      ],\n    },\n    include: { days: { orderBy: { dayNumber: \"asc\" }, include: { destination: true } } },\n  });\n\n  if (!itinerary) {\n    return {\n      found: false,\n      reason: `No published package matching \"${args.titleOrSlug}\" was found. Do not guess a price or itinerary for it — tell the user it needs to be confirmed, or suggest they browse /packages.`,\n    };\n  }\n\n  return {\n    found: true,"
  },
  "ingestion": {
    "path": "src/lib/ai/ingestion.ts",
    "startLine": 41,
    "code": "export function chunkText(text: string): string[] {\n  const normalized = text.replace(/\\r\\n/g, \"\\n\").replace(/\\n{3,}/g, \"\\n\\n\").trim();\n  if (!normalized) return [];\n\n  const paragraphs = normalized.split(/\\n\\n+/);\n  const chunks: string[] = [];\n  let current = \"\";\n\n  for (const paragraph of paragraphs) {\n    if (paragraph.length > TARGET_CHUNK_CHARS) {\n      if (current) {\n        chunks.push(current.trim());\n        current = \"\";\n      }\n      for (let i = 0; i < paragraph.length; i += TARGET_CHUNK_CHARS - CHUNK_OVERLAP_CHARS) {\n        chunks.push(paragraph.slice(i, i + TARGET_CHUNK_CHARS).trim());"
  },
  "retrieval": {
    "path": "src/lib/ai/retrieval.ts",
    "startLine": 164,
    "code": "    SELECT\n      c.\"id\"           AS \"chunkId\",\n      c.\"documentId\"   AS \"documentId\",\n      d.\"title\"        AS \"title\",\n      d.\"category\"     AS \"category\",\n      d.\"sourceType\"::text AS \"sourceType\",\n      c.\"content\"      AS \"content\",\n      (c.\"embedding\" <=> ${vectorLiteral}::vector) AS \"distance\"\n    FROM \"KnowledgeChunk\" c\n    JOIN \"KnowledgeDocument\" d ON d.\"id\" = c.\"documentId\"\n    WHERE c.\"agencyId\" = ${agencyId}\n      AND c.\"visibility\"::text = ANY(${visibility.map(String)}::text[])\n      AND c.\"embedding\" IS NOT NULL\n      AND d.\"status\" = 'PUBLISHED'\n      AND (c.\"embedding\" <=> ${vectorLiteral}::vector) <= ${MAX_COSINE_DISTANCE}\n    ORDER BY c.\"embedding\" <=> ${vectorLiteral}::vector\n    LIMIT ${limit}\n  `;\n\n  return rows.map((r) => ({ ...r, distance: Number(r.distance) }));"
  },
  "assistant": {
    "path": "src/lib/ai/assistant.ts",
    "startLine": 67,
    "code": "  for (let round = 0; round <= MAX_TOOL_ROUNDS; round++) {\n    const result = await provider.complete({ messages, tools });\n\n    if (result.toolCalls.length === 0) {\n      return result.content.trim() || FALLBACK_REPLY;\n    }\n\n    // Record the assistant's tool-call turn, then run every requested tool\n    // and feed each result back before asking the model to continue. Tool\n    // calls within one round run independently of each other, matching how\n    // providers that support parallel tool use expect results returned.\n    messages.push({ role: \"assistant\", content: result.content, toolCalls: result.toolCalls });\n\n    for (const call of result.toolCalls) {\n      const toolResult = await executeTool(call.name, call.arguments);\n      observe?.({ name: call.name, arguments: call.arguments, result: toolResult });\n      messages.push({\n        role: \"tool\",\n        content: JSON.stringify(toolResult),\n        toolCallId: call.id,\n        toolName: call.name,\n      });"
  }
} as const satisfies Record<string, Snippet>;
