/**
 * The vertical cut's narration: when each line is spoken, and what the caption
 * on screen reads while it is.
 *
 * GENERATED by video/build-vertical-vo.mjs — do not edit by hand.
 *
 * `caption` is deliberately shorter than `text`. The line is what is said; the
 * caption is what fits on a phone at a size worth reading, for the viewers who
 * meet the video muted — which on TikTok is most of them.
 */
export type VerticalLine = { id: string; start: number; end: number; text: string; caption: string };

export const VERTICAL_VO_DURATION = 44.904;

export const VERTICAL_VO: VerticalLine[] = [
  {
    "id": "hook",
    "start": 0,
    "end": 2.81,
    "text": "I built this travel website for a client in Bhutan.",
    "caption": "I built this travel website\nfor a client in Bhutan"
  },
  {
    "id": "platform",
    "start": 2.81,
    "end": 9.59,
    "text": "Twenty-nine tour packages. All twenty districts. Day-by-day itineraries, with real prices.",
    "caption": "29 tour packages\nAll 20 districts\nReal prices"
  },
  {
    "id": "backend",
    "start": 9.59,
    "end": 16.07,
    "text": "Behind it — forty API routes, thirty-four database models, five kinds of account.",
    "caption": "40 API routes\n34 database models\n5 kinds of account"
  },
  {
    "id": "turn",
    "start": 16.07,
    "end": 18.11,
    "text": "Then I wanted more than a website.",
    "caption": "Then I wanted more\nthan a website"
  },
  {
    "id": "ai",
    "start": 18.11,
    "end": 22.93,
    "text": "So I built an AI travel assistant, and put it inside the site.",
    "caption": "So I built an\nAI travel assistant"
  },
  {
    "id": "knowledge",
    "start": 22.93,
    "end": 31.42,
    "text": "It doesn't answer from general AI knowledge. I gave it its own — fifty-seven documents about Bhutan travel, searchable by meaning.",
    "caption": "Not general AI knowledge —\n57 documents about Bhutan,\nsearchable by meaning"
  },
  {
    "id": "rag",
    "start": 31.42,
    "end": 38.57,
    "text": "Ask it about Bhutan's daily fee, and it searches that first, then answers from what it actually found.",
    "caption": "It searches that first,\nthen answers from\nwhat it found"
  },
  {
    "id": "everywhere",
    "start": 38.57,
    "end": 40.06,
    "text": "Now it's on every page.",
    "caption": "Now it's on every page"
  },
  {
    "id": "cta",
    "start": 40.06,
    "end": 44.9,
    "text": "I'm Jambay, and I build websites like this. Jambayang dot com.",
    "caption": "I build websites like this\njambayang.com"
  }
];
