/**
 * When each line of the voiceover is spoken, in seconds into
 * public/audio/voiceover.mp3.
 *
 * GENERATED by video/build-vo-timing.mjs — do not edit by hand. The chapter
 * table reads it so the visuals are cut to the narration rather than the other
 * way round. Re-run after regenerating the voiceover.
 */
export type VoiceoverLine = { id: string; start: number; end: number; text: string };

export const VOICEOVER_DURATION = 98.534;

export const VOICEOVER: VoiceoverLine[] = [
  {
    "id": "idea",
    "start": 0,
    "end": 5.98,
    "text": "I wanted to build something for travelers discovering Bhutan. So I started building DTT Bhutan."
  },
  {
    "id": "foundation",
    "start": 5.98,
    "end": 13.85,
    "text": "I started with the foundation — the website itself. Fifty-nine pages, ninety-eight components, built on Next.js."
  },
  {
    "id": "design",
    "start": 13.85,
    "end": 21.17,
    "text": "The goal was simple: make discovering Bhutan feel intuitive. The header, the hero, the tours, the destinations, the travel guide."
  },
  {
    "id": "travel",
    "start": 21.17,
    "end": 30.75,
    "text": "Then I built the actual travel experience. Twenty-nine tour packages. All twenty dzongkhags. Day-by-day itineraries — and a custom tour builder for everything else."
  },
  {
    "id": "backend",
    "start": 30.75,
    "end": 38.24,
    "text": "Behind the interface, the backend that powers it. Forty API routes, each one validated before it ever touches the database."
  },
  {
    "id": "database",
    "start": 38.24,
    "end": 44.59,
    "text": "The data had to be structured too. Thirty-four models in Prisma, on PostgreSQL, hosted on Supabase."
  },
  {
    "id": "auth",
    "start": 44.59,
    "end": 50.32,
    "text": "Accounts and roles — travellers, guides, hotels, transport operators, and the agency itself."
  },
  {
    "id": "pivot",
    "start": 50.32,
    "end": 58.87,
    "text": "The website was working. But I wasn't finished. I wanted visitors to have someone they could ask. So I built an AI travel assistant."
  },
  {
    "id": "aibuild",
    "start": 58.87,
    "end": 65.81,
    "text": "I built it as its own AI layer. One interface, three providers, and eight tools that read real data."
  },
  {
    "id": "knowledge",
    "start": 65.81,
    "end": 75.78,
    "text": "I didn't want it answering from general AI knowledge. So I built a knowledge layer around Bhutan travel information — fifty-seven documents, chunked, embedded, and searchable."
  },
  {
    "id": "rag",
    "start": 75.78,
    "end": 82.8,
    "text": "Ask it about the Sustainable Development Fee, and it searches that knowledge first — then answers from what it actually found."
  },
  {
    "id": "memory",
    "start": 82.8,
    "end": 85.26,
    "text": "It keeps track of the conversation, too."
  },
  {
    "id": "integration",
    "start": 85.26,
    "end": 91.87,
    "text": "Finally, I brought it into the website. DTT Bhutan now had its own AI travel assistant."
  },
  {
    "id": "finale",
    "start": 91.87,
    "end": 98.53,
    "text": "From an idea… to a website… to an AI travel assistant built into it. DTT Bhutan. Built for travelers discovering Bhutan."
  }
];
