/**
 * Downloads the website's two typefaces so the render needs no network.
 *
 * Run from video/: node fetch-fonts.mjs
 *
 * Fraunces and Plus Jakarta Sans are what DTT Bhutan itself loads (see
 * src/app/layout.tsx in the app), and a title card in a different face would
 * undo the film's claim to be showing one product. A <link> to Google Fonts
 * works in the studio but not in the render container, whose proxy Chromium
 * won't trust — and a video that silently falls back to Helvetica when the
 * network is unavailable is worse than one that carries its fonts.
 *
 * Only the latin subsets are kept: the film has no other script in it.
 */
import fs from "node:fs";
import path from "node:path";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,700" +
  "&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap";

// Google serves woff2 only to browsers it recognises.
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUT = "public/fonts";
fs.mkdirSync(OUT, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

/** Splits the stylesheet into its @font-face blocks, keeping each one's own
 * family, weight and unicode-range rather than guessing them back. */
const blocks = css.split("@font-face").slice(1);
const kept = [];
let n = 0;

for (const block of blocks) {
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? "";
  // Everything the film renders is latin; the other subsets are dead weight.
  if (range && !/U\+0000-00FF|U\+0100-02[AB]F/.test(range)) continue;

  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
  if (!url || !family) continue;

  const name = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${n++}.woff2`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  fs.writeFileSync(path.join(OUT, name), Buffer.from(await res.arrayBuffer()));

  kept.push({ family, weight, file: name, range });
  console.log(`  ${name.padEnd(34)} ${family} ${weight}`);
}

const faces = kept
  .map(
    ({ family, weight, file, range }) => `@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: block;
  src: url('./fonts/${file}') format('woff2');${range ? `\n  unicode-range: ${range};` : ""}
}`
  )
  .join("\n\n");

fs.writeFileSync(
  "public/fonts.css",
  `/* GENERATED by video/fetch-fonts.mjs — the site's own typefaces, carried with
   the project so a render never depends on the network. */\n\n${faces}\n`
);

console.log(`\n${kept.length} font files + public/fonts.css`);
